name: build

on:
  pull_request: {}
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          # TODO: build on 'windows-latest'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8

      # Clang is seemingly already installed on Ubuntu but fails to build the project with errors
      # like "file not found" for `#include <string>`. Explicitly (re?)installing fixes things.
      - run: sudo apt-get install clang
        if: matrix.os == 'ubuntu-latest'

      - name: Build native library
        run: |
          cmake -S quickjs/jvm/ -B build/jni/ -DQUICKJS_VERSION="$(cat quickjs/common/native/quickjs/VERSION)"
          cmake --build build/jni/ --verbose
          mkdir -p quickjs/jvm/src/main/resources/
          cp -v build/jni/libquickjs.* quickjs/jvm/src/main/resources/

      - run: ./gradlew :quickjs:jvm:build

      - uses: actions/upload-artifact@v2
        with:
          name: jvm-native-libraries
          path: quickjs/jvm/src/main/resources/*
          if-no-files-found: error

  android:
    # We build on a Mac to get hardware acceleration for the Android emulator.
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8

      - run: ./gradlew :quickjs:android:build
