name: release

on:
  push:
    tags:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8

      - run: ./gradlew :quickjs:android:build

      - uses: actions/upload-artifact@v2
        with:
          name: quickjs-jvm.jar
          path: quickjs/jvm/build/libs/*.jar
          if-no-files-found: error

      - uses: ffurrer2/extract-release-notes@v1
        id: release_notes

      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: |
            quickjs/android/build/outputs/aar/*-release.aar
            quickjs/jvm/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
